version: '3'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/code/app
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/code/app
